version: '3'
volumes:
  livewire-db:
services:
  livewire:
    image: thecodingmachine/php:8.0-v4-apache-node14
    container_name: livewire
    ports:
      - "8088:80"
      - "3010:3000"
      - "3011:3001"
    volumes:
      - .:/var/www/html:cached
    environment:
      APACHE_DOCUMENT_ROOT: public/
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_SQLITE3: 1
      PHP_EXTENSION_PDO_SQLITE: 1
  livewire-db:
    image: mysql:8.0.22
    ports:
      - "3304:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: livewire
      MYSQL_USER: livewire
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - livewire-db:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
